package com.google.android.DemoKit;

public enum Protocols {
	SYNC, COM, MODE, SETAVATAR, DJEMBE, SETID, SETNCOMENABLE, 
	GETPATTERN,PATTERN,CLEARRHYTHM,USESFXR,SETSOUNDCHOICE,
	USEINSTRUMENT,USESONG,DIRECTCONTROL,SACWEIGHTS, SEPARATION, ALGINMENT, COHESION,
	ORBITCENTER,ORBITAVATAR,ORBITINLINE,FORMATION,BREATH1, BREATH2,
	FOLLOWINLINE, FOLLOWMOUSE, VMINTERVAL,
	STOPALL, STOP,FORWARD,BACKWARD, ROTLEFT, ROTRIGHT,
	LEFTMOTOR, RIGHTMOTOR,
	SMOOTH,
	ROTATETO, 
	DORHYTHMMOVE,
	DIVUP, DIVDOWN,
	HEADMOTOR,
	NEIGHBORBOUND, DANCE,EUDANSE, WNDANCE,
	TEMPOUP,TEMPODOWN,SETTEMPO, CHOOSESONG,
	TIMESLOOP,
	MAPPING,
	REUC, SEUC, SILENCE,
	FNOW,
	WANDERTHENFOLLOW,WANDERTHENORBIT,WTFIL,WTOIL,
	WANDERALL, WANDER,
	CONTROLLER,
	MOVE,
	STARTMOVE, STOPMOVE,
	TOGGLEBEACON, SETBEACONRADIUS, BEACON,
	POSITION,
	;
	
	/*
	int protocol;
	ClientProtocols(int code) {
        this.protocol = code;

    }
    */
}
