package com.google.android.DemoKit;

public enum ServerCode {
	SYNC, COM, MODE, DJEMBE, SETID, GETPATTERN, PATTERN, AVATARPATTERN, CLEARRHYTHM, USESFXR, DIRECTCONTROL,
	SACWEIGHTS, SEPARATION, ALIGNMENT, COHESION,
	ORBITCENTER, ORBIT, ORBITAVATAR,ORBITINLINE,
	FORMATION,
	BREATH1, BREATH2,
	FOLLOWINLINE, FOLLOWMOUSE,
	VMINTERVAL,
	STOPALL,
	FORWARD, BACKWARD,ROTLEFT,ROTRIGHT,
	LEFTMOTOR,RIGHTMOTOR,
	NEIGHBORBOUND,
	DANCE, EUDANCE, WNDNCE,
	TEMPOUP,TEMPODOWN, SETTEMPO,
	MAPPING,
	REUC,SEUC,
	SILENCE,
	FNOW,
	WANDERTHENFOLLOW, WANDERTHENORBIT, WTFIL,WTOIL,
	WANDERALL,
	CONTROLLER,
	MOVE,
	TOGGLEBEACON,
	BEACON,
	POSITION,
	
	
	
	;

}
